version: "3"
services:

  el-client:
    hostname: el-client
    container_name: el-client
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    command: |
      --datadir=/data
    networks:
      gnosis_net:
        ipv4_address: 192.168.32.100
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - /home/$USER/gnosis/el-client:/data
      - /home/$USER/gnosis/jwtsecret/jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=xdai
      - NETHERMIND_JSONRPCCONFIG_ENABLED=true
      - NETHERMIND_JSONRPCCONFIG_HOST=192.168.32.100
      - NETHERMIND_JSONRPCCONFIG_PORT=8545
      - NETHERMIND_JSONRPCCONFIG_JWTSECRETFILE=/jwtsecret
      - NETHERMIND_JSONRPCCONFIG_ENGINEHOST=192.168.32.100
      - NETHERMIND_JSONRPCCONFIG_ENGINEPORT=8551
      - NETHERMIND_MERGECONFIG_ENABLED=true
    logging:
      driver: "local"

  cl-client:
    user: "${PUID:-1000}
    hostname: cl-client
    container_name: cl-client
    image: consensys/teku:latest
    restart: always
    depends_on:
      - el-client
    command: |
      --network=gnosis
      --data-base-path=/data
      --ee-endpoint=http://192.168.32.100:8551
      --ee-jwt-secret-file=/jwtsecret
      --eth1-deposit-contract-max-request-size=8000
      --p2p-advertised-ip=$WAN_IP
      --log-destination=CONSOLE
      --validator-keys=/data/validator/keys:/data/validator/passwords
      --validators-proposer-default-fee-recipient=$FEE_RECIPIENT
      --validators-keystore-locking-enabled=false
      --validators-graffiti=$GRAFFITI
      --initial-state=${CHECKPOINT_URL}/eth/v2/debug/beacon/states/finalized
    networks:
      gnosis_net:
        ipv4_address: 192.168.32.101
    ports:
      - 9000:9000 # p2p
    volumes:
      - /home/$USER/gnosis/cl-client:/data
      - /home/$USER/gnosis/jwtsecret/jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Xmx4g
    logging:
      driver: "local"

networks:
  gnosis_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.32.0/24
